//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    using CRM11.MODEL;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewCRMEntities : DbContext
    {
        public NewCRMEntities()
            : base("name=NewCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmpRoleRelation> EmpRoleRelation { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RolePerRelationship> RolePerRelationship { get; set; }
        public virtual DbSet<VipPermssion> VipPermssion { get; set; }
        public virtual DbSet<WorkFLow> WorkFLow { get; set; }
        public virtual DbSet<WorkFlowApply> WorkFlowApply { get; set; }
        public virtual DbSet<WorkFlowApplyDetail> WorkFlowApplyDetail { get; set; }
        public virtual DbSet<WorkFlowBLLBranchNode> WorkFlowBLLBranchNode { get; set; }
        public virtual DbSet<WorkFlowNode> WorkFlowNode { get; set; }
        public virtual DbSet<WorkFlowNodeRole> WorkFlowNodeRole { get; set; }
    }
}
