//------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Respository
{
    
    public partial class DbSession:CRM11.IRespository.IDbSession
    {       
          CRM11.IRespository.IDepartmentRespository _DepartmentRespository;
    
          public CRM11.IRespository.IDepartmentRespository Department 
    	  { 
             get
            {
    		  if(_DepartmentRespository == null)
              {
                 _DepartmentRespository = new  DepartmentRespository();
                 return _DepartmentRespository;
              }
              return  _DepartmentRespository;
            }
    	  }
    
          CRM11.IRespository.IEmployeeRespository _EmployeeRespository;
    
          public CRM11.IRespository.IEmployeeRespository Employee 
    	  { 
             get
            {
    		  if(_EmployeeRespository == null)
              {
                 _EmployeeRespository = new  EmployeeRespository();
                 return _EmployeeRespository;
              }
              return  _EmployeeRespository;
            }
    	  }
    
          CRM11.IRespository.IEmpRoleRelationRespository _EmpRoleRelationRespository;
    
          public CRM11.IRespository.IEmpRoleRelationRespository EmpRoleRelation 
    	  { 
             get
            {
    		  if(_EmpRoleRelationRespository == null)
              {
                 _EmpRoleRelationRespository = new  EmpRoleRelationRespository();
                 return _EmpRoleRelationRespository;
              }
              return  _EmpRoleRelationRespository;
            }
    	  }
    
          CRM11.IRespository.IPermissionRespository _PermissionRespository;
    
          public CRM11.IRespository.IPermissionRespository Permission 
    	  { 
             get
            {
    		  if(_PermissionRespository == null)
              {
                 _PermissionRespository = new  PermissionRespository();
                 return _PermissionRespository;
              }
              return  _PermissionRespository;
            }
    	  }
    
          CRM11.IRespository.IRoleRespository _RoleRespository;
    
          public CRM11.IRespository.IRoleRespository Role 
    	  { 
             get
            {
    		  if(_RoleRespository == null)
              {
                 _RoleRespository = new  RoleRespository();
                 return _RoleRespository;
              }
              return  _RoleRespository;
            }
    	  }
    
          CRM11.IRespository.IRolePerRelationshipRespository _RolePerRelationshipRespository;
    
          public CRM11.IRespository.IRolePerRelationshipRespository RolePerRelationship 
    	  { 
             get
            {
    		  if(_RolePerRelationshipRespository == null)
              {
                 _RolePerRelationshipRespository = new  RolePerRelationshipRespository();
                 return _RolePerRelationshipRespository;
              }
              return  _RolePerRelationshipRespository;
            }
    	  }
    
          CRM11.IRespository.IVipPermssionRespository _VipPermssionRespository;
    
          public CRM11.IRespository.IVipPermssionRespository VipPermssion 
    	  { 
             get
            {
    		  if(_VipPermssionRespository == null)
              {
                 _VipPermssionRespository = new  VipPermssionRespository();
                 return _VipPermssionRespository;
              }
              return  _VipPermssionRespository;
            }
    	  }
    
          CRM11.IRespository.IWorkFLowRespository _WorkFLowRespository;
    
          public CRM11.IRespository.IWorkFLowRespository WorkFLow 
    	  { 
             get
            {
    		  if(_WorkFLowRespository == null)
              {
                 _WorkFLowRespository = new  WorkFLowRespository();
                 return _WorkFLowRespository;
              }
              return  _WorkFLowRespository;
            }
    	  }
    
          CRM11.IRespository.IWorkFlowApplyRespository _WorkFlowApplyRespository;
    
          public CRM11.IRespository.IWorkFlowApplyRespository WorkFlowApply 
    	  { 
             get
            {
    		  if(_WorkFlowApplyRespository == null)
              {
                 _WorkFlowApplyRespository = new  WorkFlowApplyRespository();
                 return _WorkFlowApplyRespository;
              }
              return  _WorkFlowApplyRespository;
            }
    	  }
    
          CRM11.IRespository.IWorkFlowApplyDetailRespository _WorkFlowApplyDetailRespository;
    
          public CRM11.IRespository.IWorkFlowApplyDetailRespository WorkFlowApplyDetail 
    	  { 
             get
            {
    		  if(_WorkFlowApplyDetailRespository == null)
              {
                 _WorkFlowApplyDetailRespository = new  WorkFlowApplyDetailRespository();
                 return _WorkFlowApplyDetailRespository;
              }
              return  _WorkFlowApplyDetailRespository;
            }
    	  }
    
          CRM11.IRespository.IWorkFlowBLLBranchNodeRespository _WorkFlowBLLBranchNodeRespository;
    
          public CRM11.IRespository.IWorkFlowBLLBranchNodeRespository WorkFlowBLLBranchNode 
    	  { 
             get
            {
    		  if(_WorkFlowBLLBranchNodeRespository == null)
              {
                 _WorkFlowBLLBranchNodeRespository = new  WorkFlowBLLBranchNodeRespository();
                 return _WorkFlowBLLBranchNodeRespository;
              }
              return  _WorkFlowBLLBranchNodeRespository;
            }
    	  }
    
          CRM11.IRespository.IWorkFlowNodeRespository _WorkFlowNodeRespository;
    
          public CRM11.IRespository.IWorkFlowNodeRespository WorkFlowNode 
    	  { 
             get
            {
    		  if(_WorkFlowNodeRespository == null)
              {
                 _WorkFlowNodeRespository = new  WorkFlowNodeRespository();
                 return _WorkFlowNodeRespository;
              }
              return  _WorkFlowNodeRespository;
            }
    	  }
    
          CRM11.IRespository.IWorkFlowNodeRoleRespository _WorkFlowNodeRoleRespository;
    
          public CRM11.IRespository.IWorkFlowNodeRoleRespository WorkFlowNodeRole 
    	  { 
             get
            {
    		  if(_WorkFlowNodeRoleRespository == null)
              {
                 _WorkFlowNodeRoleRespository = new  WorkFlowNodeRoleRespository();
                 return _WorkFlowNodeRoleRespository;
              }
              return  _WorkFlowNodeRoleRespository;
            }
    	  }
    
    }
}
