//------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.IRespository
{
    
    public partial interface IDbSession
    {
        
       
          CRM11.IRespository.IDepartmentRespository Department 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IEmployeeRespository Employee 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IEmpRoleRelationRespository EmpRoleRelation 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IPermissionRespository Permission 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IRoleRespository Role 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IRolePerRelationshipRespository RolePerRelationship 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IVipPermssionRespository VipPermssion 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IWorkFLowRespository WorkFLow 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IWorkFlowApplyRespository WorkFlowApply 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IWorkFlowApplyDetailRespository WorkFlowApplyDetail 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IWorkFlowBLLBranchNodeRespository WorkFlowBLLBranchNode 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IWorkFlowNodeRespository WorkFlowNode 
    	  { 
    		get;
    	  }
    
          CRM11.IRespository.IWorkFlowNodeRoleRespository WorkFlowNodeRole 
    	  { 
    		get;
    	  }
    
    }
}
