//------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.Service
{
    
    public partial class ServiceDbSession:CRM11.IService.IServiceDbSession
    {       
          CRM11.IService.IDepartmentService _DepartmentService;
    
          public CRM11.IService.IDepartmentService Department 
    	  { 
             get
            {
    		  if(_DepartmentService == null)
              {
                 _DepartmentService = new  DepartmentService();
                 return _DepartmentService;
              }
              return  _DepartmentService;
            }
    	  }
    
          CRM11.IService.IEmployeeService _EmployeeService;
    
          public CRM11.IService.IEmployeeService Employee 
    	  { 
             get
            {
    		  if(_EmployeeService == null)
              {
                 _EmployeeService = new  EmployeeService();
                 return _EmployeeService;
              }
              return  _EmployeeService;
            }
    	  }
    
          CRM11.IService.IEmpRoleRelationService _EmpRoleRelationService;
    
          public CRM11.IService.IEmpRoleRelationService EmpRoleRelation 
    	  { 
             get
            {
    		  if(_EmpRoleRelationService == null)
              {
                 _EmpRoleRelationService = new  EmpRoleRelationService();
                 return _EmpRoleRelationService;
              }
              return  _EmpRoleRelationService;
            }
    	  }
    
          CRM11.IService.IPermissionService _PermissionService;
    
          public CRM11.IService.IPermissionService Permission 
    	  { 
             get
            {
    		  if(_PermissionService == null)
              {
                 _PermissionService = new  PermissionService();
                 return _PermissionService;
              }
              return  _PermissionService;
            }
    	  }
    
          CRM11.IService.IRoleService _RoleService;
    
          public CRM11.IService.IRoleService Role 
    	  { 
             get
            {
    		  if(_RoleService == null)
              {
                 _RoleService = new  RoleService();
                 return _RoleService;
              }
              return  _RoleService;
            }
    	  }
    
          CRM11.IService.IRolePerRelationshipService _RolePerRelationshipService;
    
          public CRM11.IService.IRolePerRelationshipService RolePerRelationship 
    	  { 
             get
            {
    		  if(_RolePerRelationshipService == null)
              {
                 _RolePerRelationshipService = new  RolePerRelationshipService();
                 return _RolePerRelationshipService;
              }
              return  _RolePerRelationshipService;
            }
    	  }
    
          CRM11.IService.IVipPermssionService _VipPermssionService;
    
          public CRM11.IService.IVipPermssionService VipPermssion 
    	  { 
             get
            {
    		  if(_VipPermssionService == null)
              {
                 _VipPermssionService = new  VipPermssionService();
                 return _VipPermssionService;
              }
              return  _VipPermssionService;
            }
    	  }
    
          CRM11.IService.IWorkFLowService _WorkFLowService;
    
          public CRM11.IService.IWorkFLowService WorkFLow 
    	  { 
             get
            {
    		  if(_WorkFLowService == null)
              {
                 _WorkFLowService = new  WorkFLowService();
                 return _WorkFLowService;
              }
              return  _WorkFLowService;
            }
    	  }
    
          CRM11.IService.IWorkFlowApplyService _WorkFlowApplyService;
    
          public CRM11.IService.IWorkFlowApplyService WorkFlowApply 
    	  { 
             get
            {
    		  if(_WorkFlowApplyService == null)
              {
                 _WorkFlowApplyService = new  WorkFlowApplyService();
                 return _WorkFlowApplyService;
              }
              return  _WorkFlowApplyService;
            }
    	  }
    
          CRM11.IService.IWorkFlowApplyDetailService _WorkFlowApplyDetailService;
    
          public CRM11.IService.IWorkFlowApplyDetailService WorkFlowApplyDetail 
    	  { 
             get
            {
    		  if(_WorkFlowApplyDetailService == null)
              {
                 _WorkFlowApplyDetailService = new  WorkFlowApplyDetailService();
                 return _WorkFlowApplyDetailService;
              }
              return  _WorkFlowApplyDetailService;
            }
    	  }
    
          CRM11.IService.IWorkFlowBLLBranchNodeService _WorkFlowBLLBranchNodeService;
    
          public CRM11.IService.IWorkFlowBLLBranchNodeService WorkFlowBLLBranchNode 
    	  { 
             get
            {
    		  if(_WorkFlowBLLBranchNodeService == null)
              {
                 _WorkFlowBLLBranchNodeService = new  WorkFlowBLLBranchNodeService();
                 return _WorkFlowBLLBranchNodeService;
              }
              return  _WorkFlowBLLBranchNodeService;
            }
    	  }
    
          CRM11.IService.IWorkFlowNodeService _WorkFlowNodeService;
    
          public CRM11.IService.IWorkFlowNodeService WorkFlowNode 
    	  { 
             get
            {
    		  if(_WorkFlowNodeService == null)
              {
                 _WorkFlowNodeService = new  WorkFlowNodeService();
                 return _WorkFlowNodeService;
              }
              return  _WorkFlowNodeService;
            }
    	  }
    
          CRM11.IService.IWorkFlowNodeRoleService _WorkFlowNodeRoleService;
    
          public CRM11.IService.IWorkFlowNodeRoleService WorkFlowNodeRole 
    	  { 
             get
            {
    		  if(_WorkFlowNodeRoleService == null)
              {
                 _WorkFlowNodeRoleService = new  WorkFlowNodeRoleService();
                 return _WorkFlowNodeRoleService;
              }
              return  _WorkFlowNodeRoleService;
            }
    	  }
    
    }
}
