//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.EmpRoleRelation = new HashSet<EmpRoleRelation>();
            this.RolePerRelationship = new HashSet<RolePerRelationship>();
        }
    
        public int roleId { get; set; }
        public Nullable<int> roleDepId { get; set; }
        public string roleName { get; set; }
        public bool roleIsDel { get; set; }
        public System.DateTime roleAddTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpRoleRelation> EmpRoleRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolePerRelationship> RolePerRelationship { get; set; }
        public virtual Department Department { get; set; }
    }
}
