//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFLow
    {
        public int wfId { get; set; }
        public string wfName { get; set; }
        public string wfHtmlSrc { get; set; }
        public bool wfIsDel { get; set; }
        public System.DateTime wfAddtime { get; set; }
    }
}
