//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowApplyDetail
    {
        public int wfadId { get; set; }
        public int wfadApplyId { get; set; }
        public int wfadCurNodeId { get; set; }
        public int wfadUserId { get; set; }
        public string wfadContent { get; set; }
        public short wfadOperation { get; set; }
        public System.DateTime wfadAddTime { get; set; }
        public bool wfadIsDel { get; set; }
    }
}
