//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM11.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowNode
    {
        public int wfnId { get; set; }
        public int wfnWFId { get; set; }
        public string wfnName { get; set; }
        public int wfnPrevNodeId { get; set; }
        public int wfnNextNodeId { get; set; }
        public short wfnType { get; set; }
        public string wfnBLLClassName { get; set; }
        public int wfnOrder { get; set; }
        public bool wfnIsDel { get; set; }
        public System.DateTime wfnAddtime { get; set; }
    }
}
