//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

  namespace CRM11.MODEL
{
using System;
using System.Collections.Generic;

public partial class Employee
{
      public Employee ToPOCO(){
			return new Employee(){
								empId=this.empId,
				empDepId=this.empDepId,
				empCnName=this.empCnName,
				empLoginName=this.empLoginName,
				empLoginPwd=this.empLoginPwd,
				empSex=this.empSex,
				empAge=this.empAge,
				empCellPhone=this.empCellPhone,
				empPhone=this.empPhone,
				empAddress=this.empAddress,
				empIsDel=this.empIsDel,
				empAddTime=this.empAddTime,
			};


       }


}
}
