//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

  namespace CRM11.MODEL
{
using System;
using System.Collections.Generic;

public partial class WorkFlowApply
{
      public WorkFlowApply ToPOCO(){
			return new WorkFlowApply(){
								wfaId=this.wfaId,
				wfaWFId=this.wfaWFId,
				wfaCurNodeId=this.wfaCurNodeId,
				wfaUserId=this.wfaUserId,
				wfaTitle=this.wfaTitle,
				wfaContent=this.wfaContent,
				wfaRemark=this.wfaRemark,
				wfaPriority=this.wfaPriority,
				wfaStatue=this.wfaStatue,
				wfaAddTime=this.wfaAddTime,
				wfaIsDel=this.wfaIsDel,
			};


       }


}
}
